CREATE TABLE `goldPicksResults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fixtureId` int NOT NULL,
	`leagueId` int NOT NULL,
	`market` varchar(20) NOT NULL,
	`selection` varchar(50) NOT NULL,
	`pModel` decimal(5,4) NOT NULL,
	`score` decimal(6,2) NOT NULL,
	`edge` decimal(6,4),
	`odd` decimal(6,2),
	`reasons` json,
	`homeTeam` varchar(255) NOT NULL,
	`awayTeam` varchar(255) NOT NULL,
	`fixtureDate` timestamp NOT NULL,
	`resultStatus` enum('pending','won','lost','void') NOT NULL DEFAULT 'pending',
	`resultOutcome` varchar(100),
	`resultScore` varchar(20),
	`resultCorners` int,
	`hitAccuracy` boolean,
	`expectedValue` decimal(8,4),
	`roiContribution` decimal(8,4),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`resolvedAt` timestamp,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `goldPicksResults_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `modelPerformanceMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` varchar(10) NOT NULL,
	`totalPicks` int NOT NULL DEFAULT 0,
	`totalWins` int NOT NULL DEFAULT 0,
	`totalLosses` int NOT NULL DEFAULT 0,
	`totalVoids` int NOT NULL DEFAULT 0,
	`winRate` decimal(5,2) NOT NULL DEFAULT '0',
	`totalStaked` decimal(12,2) NOT NULL DEFAULT '0',
	`totalReturned` decimal(12,2) NOT NULL DEFAULT '0',
	`roi` decimal(8,2) NOT NULL DEFAULT '0',
	`averageEdge` decimal(6,4) NOT NULL DEFAULT '0',
	`averageOdd` decimal(6,2) NOT NULL DEFAULT '0',
	`averagePModel` decimal(5,4) NOT NULL DEFAULT '0',
	`picksByMarket` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `modelPerformanceMetrics_id` PRIMARY KEY(`id`),
	CONSTRAINT `modelPerformanceMetrics_date_unique` UNIQUE(`date`)
);
