CREATE TABLE `picks_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fixtureId` int NOT NULL,
	`leagueName` varchar(255),
	`homeTeam` varchar(255),
	`awayTeam` varchar(255),
	`market` varchar(50) NOT NULL,
	`selection` varchar(100) NOT NULL,
	`edge` decimal(8,4) NOT NULL,
	`ev` decimal(8,4) NOT NULL,
	`odd` decimal(8,2) NOT NULL,
	`modelProb` decimal(5,4) NOT NULL,
	`confidence` int DEFAULT 0,
	`status` enum('LIVE','UPCOMING','FINISHED','CANCELLED') NOT NULL DEFAULT 'UPCOMING',
	`result` enum('pending','won','lost','void') NOT NULL DEFAULT 'pending',
	`resultDetails` json,
	`kellyFraction` decimal(5,4),
	`recommendedStake` decimal(12,2),
	`actualStake` decimal(12,2),
	`profit` decimal(12,2),
	`roi` decimal(8,2),
	`notificationSent` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `picks_history_id` PRIMARY KEY(`id`)
);
